
name: Windows
on: push

jobs:
  buildWin:
    runs-on: windows-latest
    steps:
    
    - name: checkout sources
      uses: actions/checkout@v2
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'
        modules: 'imageformats'
        aqtversion: '==1.1.6'
        extra: '--external 7z'
        
    - name: Build Laigter
      shell: cmd
      run: |
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        qmake
        make
    
