name: Ubuntu 20.04
on: push

jobs:
  buildOnUbuntu:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04 # yes, this looks redundant, but something is messed up with their Ubuntu image that causes our builds to fail

    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: add build dependencies
      run: |
        apt update
        apt install -y software-properties-common clang make wget
        add-apt-repository ppa:beineri/opt-qt-5.15.2-focal
        apt-get update
        apt install -y qt515base qt515x11extras qt515tools libgl1-mesa-dev qt515imageformats
        
    - name: build Laigter
      shell: bash
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        source /opt/qt*/bin/qt*-env.sh || true
        /opt/qt515/bin/qmake CONFIG+=release PREFIX=/usr
        make -j$(nproc)
        make INSTALL_ROOT=appdir install
        find appdir/
        mkdir -p appdir/usr/lib
        export APPIMAGE_EXTRACT_AND_RUN=1
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        if [[ "$RELEASE_VERSION" != "" ]]; then export VERSION=$RELEASE_VERSION;fi
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -extra-plugins=imageformats -appimage -verbose=2

    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: Laigter-x86_64.AppImage
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

