name: Ubuntu 16.04
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  buildOnXenial:
    runs-on: ubuntu-16.04
    container:
      image: ubuntu:16.04 # yes, this looks redundant, but something is messed up with their Ubuntu image that causes our builds to fail

    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: add build dependencies
      run: |
        apt update
        apt install -y software-properties-common g++ make wget
        add-apt-repository ppa:beineri/opt-qt-5.14.2-xenial
        apt-get update
        apt install -y qt514base qt514x11extras qt514tools libgl1-mesa-dev qt514imageformats libssl1.0.0 libssl-dev
        
        apt install -y fuse
        
    - name: build Laigter
      shell: bash
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        source /opt/qt*/bin/qt*-env.sh || true
        /opt/qt514/bin/qmake CONFIG+=release PREFIX=/usr
        make -j$(nproc)
        make INSTALL_ROOT=appdir install
        find appdir/
        mkdir -p appdir/usr/lib
        cp /lib/x86_64-linux-gnu/libssl.so.1.0.0 appdir/usr/lib
        cp /usr/lib/x86_64-linux-gnu/libssl.so appdir/usr/lib
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        if [[ "$RELEASE_VERSION" != "" ]]; then export VERSION=$RELEASE_VERSION;fi
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -extra-plugins=imageformats -appimage
        
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GHR_COMPRESS: xz
          GHR_PATH: ./Laigter*.AppImage*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
