
name: Windows
on: push

jobs:
  buildWin:
    runs-on: windows-latest
    steps:
    
    - name: checkout sources
      uses: actions/checkout@v2
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'
        modules: 'imageformats'
        arch: win64_mingw73
        aqtversion: '==1.1.6'
        extra: '--external 7z'
        
    - name: Build Laigter
      shell: cmd
      run: |
        qmake
        make
        dir
        mkdir \laigter-windows
        windeployqt --dir \laigter-windows release\laigter.exe
        copy /Y release\laigter.exe .\laigter-windows\laigter.exe
        
    
