name: MacOS
on: push
      
jobs:
  buildMac:
    runs-on: macOS-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
    - name: setup Homebrew
      shell: bash
      run: |
        rm /usr/local/bin/2to3* 
        export HOMEBREW_NO_AUTO_UPDATE=1 && export HOMEBREW_NO_INSTALL_CLEANUP=1 && brew update
        HOMEBREW_VERBOSE_USING_DOTS=1 brew reinstall --verbose qt@5
        brew link qt@5 --force
    - name: build Laigter
      shell: bash
      run: |
        export PATH="/usr/local/opt/qt@5/bin:$PATH"
        qmake CONFIG+=release PREFIX=/usr
        make -j$(nproc)
        make INSTALL_ROOT=appdir install
        find appdir/
        mkdir -p appdir/usr/lib
        macdeployqt laigter.app
        wget https://raw.githubusercontent.com/chchwy/macdeployqtfix/master/macdeployqtfix.py && chmod a+x macdeployqtfix.py
        ./macdeployqtfix.py laigter.app /usr/local/Cellar/qt/*/
        zip -r laigter-mac.zip laigter.app

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mac-artifacts
        path: laigter-mac.zip 
        
    - name: GitHub Releases
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: laigter-mac.zip
        tag: ${{ github.ref }}
