name: Ubuntu 16.04
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  buildOnXenial:
    runs-on: ubuntu-16.04
    container:
      image: ubuntu:16.04 # yes, this looks redundant, but something is messed up with their Ubuntu image that causes our builds to fail

    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: add build dependencies
      run: |
        add-apt-repository ppa:beineri/opt-qt-5.14.2-xenial
        apt-get update
        apt install -y qt514base qt514x11extras qt514tools libgl1-mesa-dev qt514imageformats libssl1.0.0
        source /opt/qt*/bin/qt*-env.sh
        
    - name: build Subsurface
      run: |
        cd ..
        qmake CONFIG+=release PREFIX=/usr
        make -j$(nproc)
        make INSTALL_ROOT=appdir install
        find appdir/
        mkdir -p appdir/usr/lib
        cp /lib/x86_64-linux-gnu/libssl.so.1.0.0 appdir/usr/lib
        cp /usr/lib/x86_64-linux-gnu/libssl.so appdir/usr/lib
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        if [[ "$TRAVIS_TAG" != "" ]]; then export VERSION=$TRAVIS_TAG;fi
        ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -extra-plugins=imageformats -appimage
        
    - name: deploy build
      run: |
        wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh Laigter*.AppImage*
